framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~
    php_errors:
        log: true

parameters:
    locale: en
    main_host: '%env(MAIN_HOST)%'
    api_host: '%env(API_HOST)%'
    console_absolute_path: '%kernel.root_dir%/../bin/console'